"""Quantity column added to the product table

Revision ID: 485989442a91
Revises: a15a5dc8191d
Create Date: 2023-06-20 02:18:19.269352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485989442a91'
down_revision = 'a15a5dc8191d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
