"""Changing the relationship between tables

Revision ID: e17a87fd41e5
Revises: 
Create Date: 2023-06-19 21:10:47.636404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a87fd41e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('category',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    # op.create_table('design',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('code', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_design_id'), 'design', ['id'], unique=False)
    # op.create_table('type',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('code', sa.String(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    # op.create_table('product',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_design', sa.Integer(), nullable=True),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('talla', sa.String(), nullable=False),
    # sa.Column('price', sa.Float(), nullable=False),
    # sa.Column('state', sa.Boolean(), nullable=False),
    # sa.Column('factory_rference', sa.String(), nullable=False),
    # sa.Column('compresion', sa.Boolean(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['id_design'], ['design.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # op.create_index(op.f('ix_product_id_design'), 'product', ['id_design'], unique=False)
    # op.create_table('subcategory',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_category', sa.Integer(), nullable=True),
    # sa.Column('code', sa.String(), nullable=False),
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['id_category'], ['category.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_subcategory_id'), 'subcategory', ['id'], unique=False)
    # op.create_index(op.f('ix_subcategory_id_category'), 'subcategory', ['id_category'], unique=False)
    # op.create_table('image',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_product', sa.Integer(), nullable=True),
    # sa.Column('url', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    # op.create_index(op.f('ix_image_id_product'), 'image', ['id_product'], unique=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_image_id_product'), table_name='image')
    # op.drop_index(op.f('ix_image_id'), table_name='image')
    # op.drop_table('image')
    # op.drop_index(op.f('ix_subcategory_id_category'), table_name='subcategory')
    # op.drop_index(op.f('ix_subcategory_id'), table_name='subcategory')
    # op.drop_table('subcategory')
    # op.drop_index(op.f('ix_product_id_design'), table_name='product')
    # op.drop_index(op.f('ix_product_id'), table_name='product')
    # op.drop_table('product')
    # op.drop_index(op.f('ix_type_id'), table_name='type')
    # op.drop_table('type')
    # op.drop_index(op.f('ix_design_id'), table_name='design')
    # op.drop_table('design')
    # op.drop_index(op.f('ix_category_id'), table_name='category')
    # op.drop_table('category')
    pass
    # ### end Alembic commands ###
