"""Tag, preview and product_tag tables were added to the database

Revision ID: ee45e3d233cc
Revises: 72d1c9cd0299
Create Date: 2023-07-15 21:42:39.817118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee45e3d233cc'
down_revision = '72d1c9cd0299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
