"""Changing the ID type of the type_subcategory table from Integer to BigInteger

Revision ID: 0056c181ddeb
Revises: 17d273d653e1
Create Date: 2023-06-19 04:12:00.726400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0056c181ddeb'
down_revision = '17d273d653e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
