"""Relaciones

Revision ID: 02a08cab541c
Revises: aeb7721f729b
Create Date: 2024-07-12 16:33:44.133616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a08cab541c'
down_revision = 'aeb7721f729b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
