"""Table Shipping added and discount field added to the other tables

Revision ID: 030a84bd1025
Revises: abb3d084cc45
Create Date: 2023-11-09 05:03:28.573600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030a84bd1025'
down_revision = 'abb3d084cc45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_ciudad', sa.String(), nullable=False),
    sa.Column('departamento', sa.String(), nullable=False),
    sa.Column('tarifa', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_id'), 'shipping', ['id'], unique=False)
    op.add_column('category', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('design', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('subcategory', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('tag', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('type', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'discount')
    op.drop_column('tag', 'discount')
    op.drop_column('subcategory', 'discount')
    op.drop_column('product', 'discount')
    op.drop_column('design', 'discount')
    op.drop_column('category', 'discount')
    op.drop_index(op.f('ix_shipping_id'), table_name='shipping')
    op.drop_table('shipping')
    # ### end Alembic commands ###
