"""Campo image_url agregado a la tabla type

Revision ID: 053545d9dc85
Revises: 6fad159e2cfb
Create Date: 2024-08-11 21:37:09.308977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053545d9dc85'
down_revision = '6fad159e2cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'image_url')
    # ### end Alembic commands ###
