"""Create tables and intermediate tables between color and product

Revision ID: 0aa49a43bb67
Revises: 9ba85bb136bd
Create Date: 2024-02-06 03:38:48.432219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa49a43bb67'
down_revision = '9ba85bb136bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_id'), 'color', ['id'], unique=False)
    op.create_table('product_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_color_color_id'), 'product_color', ['color_id'], unique=False)
    op.create_index(op.f('ix_product_color_id'), 'product_color', ['id'], unique=False)
    op.create_index(op.f('ix_product_color_product_id'), 'product_color', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_color_product_id'), table_name='product_color')
    op.drop_index(op.f('ix_product_color_id'), table_name='product_color')
    op.drop_index(op.f('ix_product_color_color_id'), table_name='product_color')
    op.drop_table('product_color')
    op.drop_index(op.f('ix_color_id'), table_name='color')
    op.drop_table('color')
    # ### end Alembic commands ###
