"""create_design_product_tables

Revision ID: 107fc06f2a22
Revises: 1bdfb8d9b190
Create Date: 2023-05-03 03:49:38.427836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107fc06f2a22'
down_revision = '1bdfb8d9b190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_id'), 'design', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('talla', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=False),
    sa.Column('factory_rference', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_design_id'), table_name='design')
    op.drop_table('design')
    # ### end Alembic commands ###
