"""Relación entre producto y orden creada

Revision ID: 113e5620ea11
Revises: d22e37696ec6
Create Date: 2024-07-12 16:12:39.769200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113e5620ea11'
down_revision = 'd22e37696ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
