"""Pack table was created

Revision ID: 17067a3ed9bd
Revises: ed44c56a8e60
Create Date: 2023-11-01 22:11:16.785265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17067a3ed9bd'
down_revision = 'ed44c56a8e60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
