"""Initial Migration

Revision ID: 17d273d653e1
Revises: a4b88b20ab62
Create Date: 2023-06-19 02:46:28.738643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d273d653e1'
down_revision = 'a4b88b20ab62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
