"""create_product_design

Revision ID: 1bdfb8d9b190
Revises: 68a6942a9d13
Create Date: 2023-05-03 03:36:48.042312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdfb8d9b190'
down_revision = '68a6942a9d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
