"""Create subcategory model

Revision ID: 1fe689c870d9
Revises: b3415c9d97ae
Create Date: 2023-02-05 22:33:02.452492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fe689c870d9'
down_revision = 'b3415c9d97ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_id'), 'subcategory', ['id'], unique=False)
    op.add_column('category', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('category', 'updated_ats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('updated_ats', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('category', 'updated_at')
    op.drop_index(op.f('ix_subcategory_id'), table_name='subcategory')
    op.drop_table('subcategory')
    # ### end Alembic commands ###
