"""create_image_type_entities]

Revision ID: 2124359452a4
Revises: bbeaf55c9190
Create Date: 2023-05-21 22:53:47.479624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2124359452a4'
down_revision = 'bbeaf55c9190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.create_index(op.f('ix_image_id_product'), 'image', ['id_product'], unique=False)
    op.add_column('product', sa.Column('id_type', sa.Integer(), nullable=True))
    op.drop_index('ix_product_id_categoria', table_name='product')
    op.create_index(op.f('ix_product_id_type'), 'product', ['id_type'], unique=False)
    op.drop_constraint('product_id_categoria_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'type', ['id_type'], ['id'])
    op.drop_column('product', 'id_categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_id_categoria_fkey', 'product', 'category', ['id_categoria'], ['id'])
    op.drop_index(op.f('ix_product_id_type'), table_name='product')
    op.create_index('ix_product_id_categoria', 'product', ['id_categoria'], unique=False)
    op.drop_column('product', 'id_type')
    op.drop_index(op.f('ix_image_id_product'), table_name='image')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_type_id'), table_name='type')
    op.drop_table('type')
    # ### end Alembic commands ###
