"""tabla type_image creada

Revision ID: 318589f5d34c
Revises: 053545d9dc85
Create Date: 2024-08-12 05:56:26.434913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318589f5d34c'
down_revision = '053545d9dc85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
