"""Campos shipping_guide_url y subtotal agregados a la tabla ordenes

Revision ID: 334343387558
Revises: 02a08cab541c
Create Date: 2024-07-22 04:00:34.566265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334343387558'
down_revision = '02a08cab541c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('shipping_guide_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'shipping_guide_url')
    op.drop_column('order', 'subtotal')
    # ### end Alembic commands ###
