"""Testing 1

Revision ID: 3ba745dd543b
Revises: 0056c181ddeb
Create Date: 2023-06-19 04:24:27.130580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba745dd543b'
down_revision = '0056c181ddeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
