"""type_name field added to type_image table

Revision ID: 3fbc3adb99e9
Revises: 308b3a60bd5a
Create Date: 2024-08-12 09:41:43.119581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbc3adb99e9'
down_revision = '308b3a60bd5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_image', sa.Column('type_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_image', 'type_name')
    # ### end Alembic commands ###
