"""Tabla size_guide creada y campos image_url agregados a las tablas subcategory y type

Revision ID: 43e58a10f6a6
Revises: bef84c320696
Create Date: 2024-08-04 03:18:12.320023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e58a10f6a6'
down_revision = 'bef84c320696'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size_guide', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('alt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_guide_id'), 'size_guide', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_guide_id'), table_name='size_guide')
    op.drop_table('size_guide')
    # ### end Alembic commands ###
