"""Tag table modified to work with the current front.

Revision ID: 459b541a7a6e
Revises: 
Create Date: 2023-11-01 20:09:05.823856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459b541a7a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_product_id', table_name='tag_product')
    op.drop_table('tag_product')
    op.add_column('tag', sa.Column('product_quantity', sa.Integer(), nullable=False))
    op.add_column('tag', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('tag', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'description')
    op.drop_column('tag', 'price')
    op.drop_column('tag', 'product_quantity')
    op.create_table('tag_product',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='tag_product_product_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tag_product_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'product_id', 'tag_id', name='tag_product_pkey')
    )
    op.create_index('ix_tag_product_id', 'tag_product', ['id'], unique=False)
    # ### end Alembic commands ###
