"""campo paid_status agregado a la tabla ordenes

Revision ID: 56068498993f
Revises: 6c43d07eb318
Create Date: 2024-07-30 12:42:18.954192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56068498993f'
down_revision = '6c43d07eb318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('paid_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'paid_status')
    # ### end Alembic commands ###
