"""Modificando relación muchos a muchos de producros y ordenes

Revision ID: 5bb038e1fe7a
Revises: 72f89d8053f5
Create Date: 2024-07-28 18:51:58.810174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb038e1fe7a'
down_revision = '72f89d8053f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_order', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_order', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_product_order_id', table_name='product_order')
    op.drop_index('ix_product_order_order_id', table_name='product_order')
    op.drop_index('ix_product_order_product_id', table_name='product_order')
    op.drop_constraint('product_order_product_id_fkey', 'product_order', type_='foreignkey')
    op.drop_constraint('product_order_order_id_fkey', 'product_order', type_='foreignkey')
    op.drop_column('product_order', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_foreign_key('product_order_order_id_fkey', 'product_order', 'order', ['order_id'], ['id'])
    op.create_foreign_key('product_order_product_id_fkey', 'product_order', 'product', ['product_id'], ['id'])
    op.create_index('ix_product_order_product_id', 'product_order', ['product_id'], unique=False)
    op.create_index('ix_product_order_order_id', 'product_order', ['order_id'], unique=False)
    op.create_index('ix_product_order_id', 'product_order', ['id'], unique=False)
    op.alter_column('product_order', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_order', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
