"""tabla type_image creada

Revision ID: 5c09a8d1cc9e
Revises: 318589f5d34c
Create Date: 2024-08-12 05:59:04.955762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c09a8d1cc9e'
down_revision = '318589f5d34c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_imgage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alt', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_imgage_id'), 'type_imgage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_imgage_id'), table_name='type_imgage')
    op.drop_table('type_imgage')
    # ### end Alembic commands ###
