"""create_product_design

Revision ID: 68a6942a9d13
Revises: bfbfe5b680f0
Create Date: 2023-05-03 03:33:21.945042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a6942a9d13'
down_revision = 'bfbfe5b680f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('category', 'nombre')
    op.add_column('subcategory', sa.Column('id_category', sa.Integer(), nullable=True))
    op.add_column('subcategory', sa.Column('code', sa.String(), nullable=False))
    op.add_column('subcategory', sa.Column('name', sa.String(), nullable=False))
    op.add_column('subcategory', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subcategory', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_subcategory_id_category'), 'subcategory', ['id_category'], unique=False)
    op.create_foreign_key(None, 'subcategory', 'category', ['id_category'], ['id'])
    op.drop_column('subcategory', 'nombre')
    op.drop_column('subcategory', 'codigo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('codigo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subcategory', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subcategory', type_='foreignkey')
    op.drop_index(op.f('ix_subcategory_id_category'), table_name='subcategory')
    op.drop_column('subcategory', 'updated_at')
    op.drop_column('subcategory', 'created_at')
    op.drop_column('subcategory', 'name')
    op.drop_column('subcategory', 'code')
    op.drop_column('subcategory', 'id_category')
    op.add_column('category', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
