"""intermediate tables type

Revision ID: 6a59cef13ff1
Revises: a38abee4a78d
Create Date: 2023-05-22 19:59:33.987056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a59cef13ff1'
down_revision = 'a38abee4a78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('compresion', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'compresion')
    # ### end Alembic commands ###
