"""Campo de texto pack agregado a la tabla product_order para identificar si el producto es un pack o no

Revision ID: 6c43d07eb318
Revises: 7c58a7dae4b1
Create Date: 2024-07-30 04:28:00.727603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c43d07eb318'
down_revision = '7c58a7dae4b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('pack', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_order', 'pack')
    # ### end Alembic commands ###
