"""campos image_url agregados a las tablas subcategory y type

Revision ID: 6fad159e2cfb
Revises: 85d3f2550792
Create Date: 2024-08-04 15:26:07.353485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fad159e2cfb'
down_revision = '85d3f2550792'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
