"""Columna quantity agregada a la tabla product_order

Revision ID: 72f89d8053f5
Revises: 334343387558
Create Date: 2024-07-23 02:27:38.419977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f89d8053f5'
down_revision = '334343387558'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_order', 'quantity')
    # ### end Alembic commands ###
