"""Volviendo a las relaciones anteriores

Revision ID: 7c58a7dae4b1
Revises: 5bb038e1fe7a
Create Date: 2024-07-28 18:59:04.960231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c58a7dae4b1'
down_revision = '5bb038e1fe7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_order', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('product_order', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_order', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_product_order_id'), 'product_order', ['id'], unique=False)
    op.create_index(op.f('ix_product_order_order_id'), 'product_order', ['order_id'], unique=False)
    op.create_index(op.f('ix_product_order_product_id'), 'product_order', ['product_id'], unique=False)
    op.create_foreign_key(None, 'product_order', 'order', ['order_id'], ['id'])
    op.create_foreign_key(None, 'product_order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_order', type_='foreignkey')
    op.drop_constraint(None, 'product_order', type_='foreignkey')
    op.drop_index(op.f('ix_product_order_product_id'), table_name='product_order')
    op.drop_index(op.f('ix_product_order_order_id'), table_name='product_order')
    op.drop_index(op.f('ix_product_order_id'), table_name='product_order')
    op.alter_column('product_order', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_order', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('product_order', 'id')
    # ### end Alembic commands ###
