"""Solving some problems with the relationships 3

Revision ID: 7e01fa333b0a
Revises: 86ca1fef8acb
Create Date: 2023-05-25 02:37:34.960454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e01fa333b0a'
down_revision = '86ca1fef8acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_id_subcategoria', table_name='product')
    op.drop_constraint('product_id_subcategoria_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'id_subcategoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_subcategoria', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_id_subcategoria_fkey', 'product', 'subcategory', ['id_subcategoria'], ['id'])
    op.create_index('ix_product_id_subcategoria', 'product', ['id_subcategoria'], unique=False)
    # ### end Alembic commands ###
