"""Tablas para manejo de ordenes creadas

Revision ID: 801b9064a2e3
Revises: e1531dbe4cd8
Create Date: 2024-07-12 15:30:37.623614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801b9064a2e3'
down_revision = 'e1531dbe4cd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('billing_addess', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.Column('de', sa.String(), nullable=True),
    sa.Column('para', sa.String(), nullable=True),
    sa.Column('isGift', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('shipping_guide', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('product_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_order_id'), 'product_order', ['id'], unique=False)
    op.create_index(op.f('ix_product_order_order_id'), 'product_order', ['order_id'], unique=False)
    op.create_index(op.f('ix_product_order_product_id'), 'product_order', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_order_product_id'), table_name='product_order')
    op.drop_index(op.f('ix_product_order_order_id'), table_name='product_order')
    op.drop_index(op.f('ix_product_order_id'), table_name='product_order')
    op.drop_table('product_order')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
