"""Campos preference y payment_id agregados a la tabla order

Revision ID: 82f37e2685fe
Revises: 8c7e6c83bc32
Create Date: 2024-08-14 19:22:14.967348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f37e2685fe'
down_revision = '8c7e6c83bc32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('preference', sa.String(), nullable=False))
    op.add_column('order', sa.Column('pyment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'pyment_id')
    op.drop_column('order', 'preference')
    # ### end Alembic commands ###
