"""campos image_url agregados a las tablas subcategory y type

Revision ID: 85d3f2550792
Revises: 43e58a10f6a6
Create Date: 2024-08-04 14:46:33.398995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d3f2550792'
down_revision = '43e58a10f6a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('type', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type', 'image_url')
    op.drop_column('subcategory', 'image_url')
    # ### end Alembic commands ###
