"""Solving some problems with the relationships

Revision ID: 867f77696a69
Revises: 3101c421c960
Create Date: 2023-05-25 02:33:51.643590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '867f77696a69'
down_revision = '3101c421c960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
