"""Solving some problems with the relationships 2

Revision ID: 86ca1fef8acb
Revises: 867f77696a69
Create Date: 2023-05-25 02:36:18.971600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ca1fef8acb'
down_revision = '867f77696a69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
