"""Code column added to the product table

Revision ID: 8914e6cfcaf3
Revises: 5fb9c4497ab0
Create Date: 2023-11-26 17:18:48.218077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8914e6cfcaf3'
down_revision = '5fb9c4497ab0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
