"""type_name field change by name

Revision ID: 8c7e6c83bc32
Revises: 3fbc3adb99e9
Create Date: 2024-08-12 21:46:58.668995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7e6c83bc32'
down_revision = '3fbc3adb99e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_image', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('type_image', 'type_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_image', sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('type_image', 'name')
    # ### end Alembic commands ###
