"""Create intermediate table between size and product

Revision ID: 9ba85bb136bd
Revises: c4a693088032
Create Date: 2024-02-04 03:45:05.083322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba85bb136bd'
down_revision = 'c4a693088032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_size_id'), 'product_size', ['id'], unique=False)
    op.create_index(op.f('ix_product_size_product_id'), 'product_size', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_size_size_id'), 'product_size', ['size_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_size_size_id'), table_name='product_size')
    op.drop_index(op.f('ix_product_size_product_id'), table_name='product_size')
    op.drop_index(op.f('ix_product_size_id'), table_name='product_size')
    op.drop_table('product_size')
    # ### end Alembic commands ###
