"""product type relationship and product subcategory relationship created. Adding color column to product

Revision ID: a15a5dc8191d
Revises: e17a87fd41e5
Create Date: 2023-06-19 21:30:44.449559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15a5dc8191d'
down_revision = 'e17a87fd41e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product', sa.Column('id_type', sa.Integer(), nullable=True))
    # op.add_column('product', sa.Column('id_subcategory', sa.Integer(), nullable=True))
    # op.add_column('product', sa.Column('color', sa.String(), nullable=True))
    # op.create_index(op.f('ix_product_id_subcategory'), 'product', ['id_subcategory'], unique=False)
    # op.create_index(op.f('ix_product_id_type'), 'product', ['id_type'], unique=False)
    # op.create_foreign_key(None, 'product', 'type', ['id_type'], ['id'])
    # op.create_foreign_key(None, 'product', 'subcategory', ['id_subcategory'], ['id'])
    # op.drop_column('product', 'factory_rference')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('product', sa.Column('factory_rference', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'product', type_='foreignkey')
    # op.drop_constraint(None, 'product', type_='foreignkey')
    # op.drop_index(op.f('ix_product_id_type'), table_name='product')
    # op.drop_index(op.f('ix_product_id_subcategory'), table_name='product')
    # op.drop_column('product', 'color')
    # op.drop_column('product', 'id_subcategory')
    # op.drop_column('product', 'id_type')
    pass
    # ### end Alembic commands ###
