"""create_image_type_entities]

Revision ID: a38abee4a78d
Revises: 2124359452a4
Create Date: 2023-05-21 23:07:24.639670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38abee4a78d'
down_revision = '2124359452a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('desription', sa.String(), nullable=False))
    op.drop_column('type', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('type', 'desription')
    # ### end Alembic commands ###
