"""Adding ID to the type_subcategory table

Revision ID: a4b88b20ab62
Revises: f8ffcddd95bc
Create Date: 2023-06-18 18:58:17.970242

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a4b88b20ab62'
down_revision = 'f8ffcddd95bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_subcategory', sa.Column('id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_type_subcategory_id'), 'type_subcategory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_subcategory_id'), table_name='type_subcategory')
    op.drop_column('type_subcategory', 'id')
    # ### end Alembic commands ###
