"""Daniel/Packs State and discount column added to the packs products

Revision ID: abb3d084cc45
Revises: aade2e720cdf
Create Date: 2023-11-05 21:47:26.256947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb3d084cc45'
down_revision = 'aade2e720cdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('pack', sa.Column('state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack', 'state')
    op.drop_column('pack', 'discount')
    # ### end Alembic commands ###
