"""Relación entre producto

Revision ID: aeb7721f729b
Revises: 113e5620ea11
Create Date: 2024-07-12 16:26:15.162416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb7721f729b'
down_revision = '113e5620ea11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
