"""Create subcategory model

Revision ID: b3415c9d97ae
Revises: 747ebe92c827
Create Date: 2023-02-05 19:16:24.446762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3415c9d97ae'
down_revision = '747ebe92c827'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('updated_ats', sa.DateTime(), nullable=False))
    op.drop_column('category', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('category', 'updated_ats')
    # ### end Alembic commands ###
