"""Solving some problems

Revision ID: b5e0c6c08963
Revises: f696e25f269f
Create Date: 2023-05-23 04:15:04.861226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e0c6c08963'
down_revision = 'f696e25f269f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
