"""create_product_relationships]

Revision ID: bbeaf55c9190
Revises: 107fc06f2a22
Create Date: 2023-05-04 03:34:09.720738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeaf55c9190'
down_revision = '107fc06f2a22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_categoria', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('id_subcategoria', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('id_disenio', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_id_categoria'), 'product', ['id_categoria'], unique=False)
    op.create_index(op.f('ix_product_id_disenio'), 'product', ['id_disenio'], unique=False)
    op.create_index(op.f('ix_product_id_subcategoria'), 'product', ['id_subcategoria'], unique=False)
    op.create_foreign_key(None, 'product', 'design', ['id_disenio'], ['id'])
    op.create_foreign_key(None, 'product', 'subcategory', ['id_subcategoria'], ['id'])
    op.create_foreign_key(None, 'product', 'category', ['id_categoria'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_index(op.f('ix_product_id_subcategoria'), table_name='product')
    op.drop_index(op.f('ix_product_id_disenio'), table_name='product')
    op.drop_index(op.f('ix_product_id_categoria'), table_name='product')
    op.drop_column('product', 'id_disenio')
    op.drop_column('product', 'id_subcategoria')
    op.drop_column('product', 'id_categoria')
    # ### end Alembic commands ###
