"""Agregar campo state en la tabla de sliders

Revision ID: bdeccd3fda15
Revises: e9a16530a4f5
Create Date: 2024-07-10 16:50:05.708386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdeccd3fda15'
down_revision = 'e9a16530a4f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slider', sa.Column('state', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slider', 'state')
    # ### end Alembic commands ###
