"""id column added to the type_design table as primary key and big integer

Revision ID: bf698dae3cda
Revises: 3ba745dd543b
Create Date: 2023-06-19 15:43:28.307920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf698dae3cda'
down_revision = '3ba745dd543b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_design', sa.Column('id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_type_design_id'), 'type_design', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_design_id'), table_name='type_design')
    op.drop_column('type_design', 'id')
    # ### end Alembic commands ###
