"""Tabla de órdenes y de productos_ordenes creadas

Revision ID: cca893de5bf8
Revises: bdeccd3fda15
Create Date: 2024-07-12 15:26:47.813715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca893de5bf8'
down_revision = 'bdeccd3fda15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
