"""Relación entre producto y orden creada

Revision ID: d22e37696ec6
Revises: 801b9064a2e3
Create Date: 2024-07-12 16:00:03.259542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22e37696ec6'
down_revision = '801b9064a2e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
