"""Adding image_url to the tag table

Revision ID: d2a54103a558
Revises: 3bd131e5d359
Create Date: 2023-07-15 21:58:41.263835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a54103a558'
down_revision = '3bd131e5d359'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'image_url')
    # ### end Alembic commands ###
