"""Solving some problems with the relationships 4

Revision ID: d3f06211cc96
Revises: 7e01fa333b0a
Create Date: 2023-05-25 02:59:09.449139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f06211cc96'
down_revision = '7e01fa333b0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
