"""Tablas para gestión de órdenes creadas

Revision ID: e1531dbe4cd8
Revises: cca893de5bf8
Create Date: 2024-07-12 15:29:58.870905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1531dbe4cd8'
down_revision = 'cca893de5bf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
