"""Tag table modified to work with the current front.

Revision ID: e798f37e0ec6
Revises: 
Create Date: 2023-11-01 20:36:53.989256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e798f37e0ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_id', 'tag_id')
    )
    op.create_index(op.f('ix_tag_product_id'), 'tag_product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_product_id'), table_name='tag_product')
    op.drop_table('tag_product')
    # ### end Alembic commands ###
