"""Editing Created at and Modified at columns of shipping's table.

Revision ID: ebf4f533d63f
Revises: 030a84bd1025
Create Date: 2023-11-09 05:17:41.586844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebf4f533d63f'
down_revision = '030a84bd1025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shipping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('shipping', 'municipio_ciudad;departamento;tarifa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping', sa.Column('municipio_ciudad;departamento;tarifa', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('shipping', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('shipping', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
