"""Pack table created

Revision ID: ed44c56a8e60
Revises: e798f37e0ec6
Create Date: 2023-11-01 21:37:52.658474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed44c56a8e60'
down_revision = 'e798f37e0ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'price')
    op.drop_column('tag', 'product_quantity')
    op.drop_column('tag', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tag', sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tag', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
