"""ïntermediate_tables_created

Revision ID: f696e25f269f
Revises: 025dc618dddb
Create Date: 2023-05-22 20:17:20.907292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f696e25f269f'
down_revision = '025dc618dddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_design',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['design.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'design_id')
    )
    op.create_index(op.f('ix_type_design_design_id'), 'type_design', ['design_id'], unique=False)
    op.create_index(op.f('ix_type_design_type_id'), 'type_design', ['type_id'], unique=False)
    op.create_table('type_subcategory',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'subcategory_id')
    )
    op.add_column('product', sa.Column('id_design', sa.Integer(), nullable=True))
    op.drop_index('ix_product_id_disenio', table_name='product')
    op.drop_index('ix_product_id_type', table_name='product')
    op.create_index(op.f('ix_product_id_design'), 'product', ['id_design'], unique=False)
    op.drop_constraint('product_id_disenio_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_id_type_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'design', ['id_design'], ['id'])
    op.drop_column('product', 'id_disenio')
    op.drop_column('product', 'id_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('id_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('id_disenio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_id_type_fkey', 'product', 'type', ['id_type'], ['id'])
    op.create_foreign_key('product_id_disenio_fkey', 'product', 'design', ['id_disenio'], ['id'])
    op.drop_index(op.f('ix_product_id_design'), table_name='product')
    op.create_index('ix_product_id_type', 'product', ['id_type'], unique=False)
    op.create_index('ix_product_id_disenio', 'product', ['id_disenio'], unique=False)
    op.drop_column('product', 'id_design')
    op.drop_table('type_subcategory')
    op.drop_index(op.f('ix_type_design_type_id'), table_name='type_design')
    op.drop_index(op.f('ix_type_design_design_id'), table_name='type_design')
    op.drop_table('type_design')
    # ### end Alembic commands ###
