"""Agregando secuencia a id de la tabla tag_product

Revision ID: f7d7d1fa7dd8
Revises: 5b8923a4c006
Create Date: 2024-01-17 05:39:08.920538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d7d1fa7dd8'
down_revision = '5b8923a4c006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tag_product', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tag_product_product_id'), 'tag_product', ['product_id'], unique=False)
    op.create_index(op.f('ix_tag_product_tag_id'), 'tag_product', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_product_tag_id'), table_name='tag_product')
    op.drop_index(op.f('ix_tag_product_product_id'), table_name='tag_product')
    op.alter_column('tag_product', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag_product', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
