"""Changing column names in Type table

Revision ID: f8ffcddd95bc
Revises: fa7d1a1ad778
Create Date: 2023-06-10 23:55:43.287482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ffcddd95bc'
down_revision = 'fa7d1a1ad778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('name', sa.String(), nullable=False))
    op.add_column('type', sa.Column('code', sa.String(), nullable=True))
    op.drop_column('type', 'desription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type', sa.Column('desription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('type', 'code')
    op.drop_column('type', 'name')
    # ### end Alembic commands ###
