"""Solving some problems with the relationships 5

Revision ID: fa7d1a1ad778
Revises: d3f06211cc96
Create Date: 2023-05-25 03:03:02.345033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7d1a1ad778'
down_revision = 'd3f06211cc96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
