"""Corrigiendo relaciones entre product y color

Revision ID: ffd098b607ae
Revises: 0aa49a43bb67
Create Date: 2024-02-06 04:04:56.762689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd098b607ae'
down_revision = '0aa49a43bb67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
